<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenFTTH.Results" Version="0.2.0" />
    <PackageReference Include="OpenFTTH.Address.API" Version="4.0.0" />
    <PackageReference Include="OpenFTTH.Address.Business" Version="4.0.0" />
    <PackageReference Include="OpenFTTH.Core" Version="3.0.0" />
    <PackageReference Include="OpenFTTH.CQRS" Version="5.2.0" />
    <PackageReference Include="OpenFTTH.Events" Version="4.0.0" />
    <PackageReference Include="OpenFTTH.EventSourcing" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenFTTH.Work.API\OpenFTTH.Work.API.csproj" />
  </ItemGroup>

</Project>
